./a.out maze6x6_1.txt | head -5;
echo "\n\n";
./a.out maze6x6_2.txt | head -5;
echo "\n\n";
./a.out maze7x15_1.txt | head -5;
echo "\n\n";
./a.out maze7x15_2.txt | head -5;
echo "\n\n";
./a.out maze15x7_1.txt | head -5;
echo "\n\n";
./a.out maze15x7_2.txt | head -5;
echo "\n\n";
